---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: seite50-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: seite50
spec:
  rules:
  - host: seite50.lab
    http:
      paths:
      - path: /api
        backend:
          serviceName: seite50-backend
          servicePort: 8080
      - path: /
        backend:
          serviceName: seite50-frontend
          servicePort: 80
